services:
- postgresql
language: python
python:
- '3.8'
install:
- pip install django-heroku
- pip install django-allauth
- pip install -r requirements-travis.txt
before_script:
- psql postgres -c "CREATE USER quickesttutor WITH PASSWORD 'qt3';"
- psql postgres -c "CREATE DATABASE tutordatabase WITH OWNER quickesttutor;"
- psql postgres -c "ALTER USER quickesttutor SUPERUSER CREATEROLE CREATEDB REPLICATION;"
- python manage.py makemigrations
- python manage.py migrate
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: Pxzl9UlYhcJVHIjPogMOytIEpHExNJkFADrLSl95YcAKLqEw+IUQNKhDFClqRAtnFxPUsSwIz25SGRy71YZ6tpt2VXWhQqAG5ZdFgcv/UnsxQJsoRFn9GQxg92aOJOcHs91IsZjXXZ5DNXWQt77VjuhHf/6HoDWo4Q7vNO4hJcBGZLp0JO6Js0NEOdWxP1gdt/ap3FmD7z+WN1noy4aSNEjLd3cLV3xA/4ClmJquMVfOYnRrYuxolUmzyawocTHiDrykRQCNMK358KxjoPjoTkkck4wyuVcALLwf0FoX7n/G5fMxtB8t15Mrcz6N4A+9U+MXmvDFCIIQ4TqzAn0rPZsQHJQl3cpOWTI58ylYDlPm4S+aKlP+R4SZc/zcG7i/NIvajphTGoQ8ml40nYx478fSPWrb5cxpn+Kt7n4uo/RyaKiaXib9QbUaFVayQHFvXE9fDcl1lrB1fS/53HxQ3ZW2sXtlzTmWnw7MAizclmjV3vGGGqTTu79cwydqr24dtyQdfysEMTWfiV0HSeOZ/YxT4FQH/xOAfyHw+uDDkSpqs4B9Y2yvPPWsG3ml2qvhV6E3Msa0Vo8UxhDfg9/feyZHI6Ig2vnKYqchX++CifC6IBBwR0wMyBrmCxJBCngd3uapN0UofVkBiTJfJ4vaFi6BxPUiDxJ8W5NuD2E/R1g=
  app: quickest-tutor-103
  on:
    repo: uva-cs3240-s20/project-103-quickesttutor
