services:
  - postgresql
language: python
python:
  - '3.8'
install:
  - pip install django-heroku
  - pip install django-allauth
  - pip install -r requirements-travis.txt
before_script:
- psql postgres -c "CREATE USER quickesttutor WITH PASSWORD 'qt3';"
- psql postgres -c "CREATE DATABASE tutordatabase WITH OWNER quickesttutor;"
- psql postgres -c "ALTER USER quickesttutor SUPERUSER CREATEROLE CREATEDB REPLICATION;"
- python manage.py makemigrations
- python manage.py migrate
script:
- python manage.py test
deploy:
  provider: heroku
  api_key: 
    secure: "VVZp/gqX0pW1y1bmvjWcb3yFSW9Mr1e9Ftv7qf+LWaAoxlQAM5Ce43gfwMX11ELF9FvsC/ZVqNR+KCJ1a9U9d7DWSVC9rSOsC3c31COhLDC8Hz4yYJa/Fl7pnft2gOVsV96WM0ptx/F8xFxkmS/RGZirRaFOvKgkZu6yQNB7YeMDzrjqYFnX7BMqGepNKYesFPFKMb3NtGWP6qPLxTJir4EqKqNPQgdA3GnbB+d9vtOXM/ab00qZIhlySyuHXes3ll1DOmjwtp+lBxnnI5MiavuyazNqxrueN85QxJVRtmMk0dL7O6xY8QidKyaAi7+CoZW0xeWRViUSGh6kdU2Axr3f0hdHVHM6xNX8UAACFUdfyR9/SAgenCw5m3gTwPCuk46nEpSWBtk6HrGlgSLsbo1XewTZQcFOQpmpjlWbtHVmmG/EMaJbCDTk0s+Jj51ZzNpb/sUV873v6YRrpm3Gxw1V6fAb5ZL/W16Ljo9PvZM76nnDtFfp44++vqrz/GpccNfKxZQL6sbHe7pShMJ7ydhVeJnqf7Fb5IUZZ6Ug7sbs1h9LUbPrIA3kPgDwc+cf9af13hfW1/4baYe3TcDp7Dt3ijtuIQuc/NysPAFjD2jkQ8cuSDPxOlg57Veqmzv3bgZ3Z/ABp55ivNy+NUIm8Sb8cPsP4zp2uSBMgt5fv94="
  app: quickest-tutor-103
  on:
    repo: uva-cs3240-s20/project-103-quickesttutor
