services:
- postgresql
language: python
python:
- '3.8'
install:
- pip install django-heroku
- pip install django-allauth
- pip install -r requirements-travis.txt
before_script:
- psql postgres -c "CREATE USER quickesttutor WITH PASSWORD 'qt3';"
- psql postgres -c "CREATE DATABASE tutordatabase WITH OWNER quickesttutor;"
- psql postgres -c "ALTER USER quickesttutor SUPERUSER CREATEROLE CREATEDB REPLICATION;"
- python manage.py makemigrations
- python manage.py migrate
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: 32ae2e88-7a88-4152-b2f0-c33c820ecd01
  app: quickest-tutor-103
  on:
    repo: uva-cs3240-s20/project-103-quickesttutor
