# Generated by Django 3.0.3 on 2020-04-11 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsession',
            name='day',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
