# Generated by Django 3.0.2 on 2020-04-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestsession',
            name='note',
        ),
        migrations.RemoveField(
            model_name='requestsession',
            name='students_class',
        ),
        migrations.AddField(
            model_name='requestsession',
            name='course',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='requestsession',
            name='description',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='requestsession',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requestsession',
            name='student_availability',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='requestsession',
            name='tutor_username',
            field=models.TextField(default='none', max_length=20),
        ),
    ]
