# Generated by Django 3.0.3 on 2020-04-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='texp',
            field=models.TextField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tmajors',
            field=models.TextField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tpn',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tsubjects',
            field=models.TextField(default='none', max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
