# Generated by Django 3.0.2 on 2020-04-12 00:26

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='user',
            name='tutorAvailibility',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(blank=True, default=datetime.datetime.now), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2020-04-12'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2020-04-12'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.TextField(default='0000000000', max_length=20),
        ),
    ]
