# Generated by Django 3.0.2 on 2020-04-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emailAddress',
            field=models.TextField(default='none', max_length=50),
        ),
    ]
