# Generated by Django 3.0.3 on 2020-04-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsession',
            name='chosen_time',
            field=models.TextField(default='none', max_length=100),
        ),
    ]
