# Generated by Django 3.0.2 on 2020-04-13 02:07

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='tutorAvailibility',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(blank=True, default=datetime.datetime.now), blank=True, null=True, size=None),
        ),
    ]
