# Generated by Django 3.0.2 on 2020-04-12 02:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200411_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tutorAvailibility',
        ),
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
