# Generated by Django 3.0.3 on 2020-04-05 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200405_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='year',
        ),
        migrations.AddField(
            model_name='tutor',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
