# Generated by Django 3.0.3 on 2020-04-12 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200411_2026'),
        ('home', '0002_auto_20200411_0611'),
    ]

    operations = [
    ]
