# Generated by Django 3.0.2 on 2020-04-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200405_0231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
        migrations.AddField(
            model_name='user',
            name='classes',
            field=models.TextField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='hourlyRate',
            field=models.TextField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.TextField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.TextField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='texp',
            field=models.TextField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='tsubjects',
            field=models.TextField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2020-04-07'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2020-04-07'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
