# Generated by Django 3.0.3 on 2020-03-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_todolist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2020-03-29'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2020-03-29'),
        ),
    ]
