# Generated by Django 3.0.3 on 2020-04-15 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200415_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsession',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestsession',
            name='username',
            field=models.TextField(default='none', max_length=1000),
        ),
        migrations.AlterField(
            model_name='requestsession',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
