# Generated by Django 3.0.2 on 2020-04-15 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200415_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestsession',
            name='note',
        ),
        migrations.RemoveField(
            model_name='requestsession',
            name='students_class',
        ),
        migrations.AddField(
            model_name='requestsession',
            name='course',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='requestsession',
            name='description',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='requestsession',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestsession',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestsession',
            name='tutor_username',
            field=models.TextField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='requestsession',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestsession',
            name='student_availability',
            field=models.DateTimeField(blank=True),
        ),
    ]
