# Generated by Django 3.0.3 on 2020-04-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_requestsession_chosen_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestsession',
            name='student_availability',
        ),
    ]
