# Generated by Django 3.0.3 on 2020-04-12 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_merge_20200412_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestsession',
            name='day',
        ),
        migrations.RemoveField(
            model_name='requestsession',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='requestsession',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isTutor',
        ),
        migrations.AddField(
            model_name='requestsession',
            name='student_availability',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
