# Generated by Django 3.0.3 on 2020-04-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200405_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='pn',
            new_name='spn',
        ),
        migrations.RemoveField(
            model_name='student',
            name='majors',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2020-04-07'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2020-04-07'),
        ),
    ]
