# Generated by Django 3.0.3 on 2020-04-15 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200415_0357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestsession',
            old_name='username',
            new_name='tutor_username',
        ),
    ]
