# Generated by Django 3.0.3 on 2020-04-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_tutor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='trate',
            field=models.TextField(default='none', max_length=500),
        ),
    ]
