# Generated by Django 3.0.3 on 2020-04-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200407_2139'),
        ('home', '0003_auto_20200407_1814'),
    ]

    operations = [
    ]
