# Generated by Django 3.0.2 on 2020-04-07 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200405_0231'),
        ('home', '0004_auto_20200405_0302'),
    ]

    operations = [
    ]
