# Generated by Django 3.0.2 on 2020-04-08 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_merge_20200407_2355'),
        ('home', '0006_auto_20200407_1921'),
    ]

    operations = [
    ]
