# Generated by Django 3.0.3 on 2020-04-08 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200407_0338'),
        ('home', '0005_merge_20200407_2355'),
    ]

    operations = [
    ]
